import type { IconType } from "react-icons";
import {
  SiNextdotjs,
  SiReact,
  SiTypescript,
  SiJavascript,
  SiPython,
  SiOpenai,
  SiAnthropic,
  SiVercel,
  SiTailwindcss,
  SiHuggingface,
  SiLangchain,
  SiPydantic,
  SiFastapi,
  SiPostgresql,
  SiSupabase,
  SiNodedotjs,
  SiDocker,
  SiGithub,
  SiGooglecloud,
} from "react-icons/si";

const iconMap: Record<string, IconType> = {
  "next.js": SiNextdotjs,
  nextjs: SiNextdotjs,
  react: SiReact,
  typescript: SiTypescript,
  javascript: SiJavascript,
  python: SiPython,
  openai: SiOpenai,
  "gpt-4": SiOpenai,
  "gpt-4o": SiOpenai,
  anthropic: SiAnthropic,
  claude: SiAnthropic,
  vercel: SiVercel,
  tailwind: SiTailwindcss,
  "tailwind css": SiTailwindcss,
  tailwindcss: SiTailwindcss,
  "hugging face": SiHuggingface,
  huggingface: SiHuggingface,
  langchain: SiLangchain,
  pydantic: SiPydantic,
  fastapi: SiFastapi,
  postgres: SiPostgresql,
  postgresql: SiPostgresql,
  supabase: SiSupabase,
  node: SiNodedotjs,
  "node.js": SiNodedotjs,
  nodejs: SiNodedotjs,
  docker: SiDocker,
  github: SiGithub,
  gcp: SiGooglecloud,
  "google cloud": SiGooglecloud,
};

export function getTechIcon(label: string): IconType | null {
  return iconMap[label.toLowerCase()] ?? null;
}
